name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.2
  fpdart: ^1.1.0
  shared_preferences: ^2.2.3
  dotted_border: ^2.1.0
  flex_color_picker: ^3.5.1
  file_picker: ^8.0.6
  audio_waveforms: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  
flutter:
  
  uses-material-design: true
  assets:
    - assets/images/